name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [typos]
        uses: crate-ci/typos@v1.14.9
